// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// simple
void simple();
RcppExport SEXP RcppGeiger_simple() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    simple();
    return R_NilValue;
END_RCPP
}
// walk
void walk();
RcppExport SEXP RcppGeiger_walk() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    walk();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"RcppGeiger_simple", (DL_FUNC) &RcppGeiger_simple, 0},
    {"RcppGeiger_walk", (DL_FUNC) &RcppGeiger_walk, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppGeiger(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
