// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// simple
void simple();
RcppExport SEXP RcppGeiger_simple() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    simple();
    return R_NilValue;
END_RCPP
}
// walk
void walk();
RcppExport SEXP RcppGeiger_walk() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    walk();
    return R_NilValue;
END_RCPP
}
