# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simple microbenchmarking examples
#'
#' @title Simple 'Geiger' micro-benchmarking examples 
#' @return None
simple <- function() {
    invisible(.Call('RcppGeiger_simple', PACKAGE = 'RcppGeiger'))
}

#' @rdname simple
walk <- function() {
    invisible(.Call('RcppGeiger_walk', PACKAGE = 'RcppGeiger'))
}

